### ISSUE TITLE
Non standard library functions

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose-core#110]
With gcc version 5.3.0 on cygwin and trying cmake build:

```
moose-core/mesh/NeuroNode.cpp:275:37: error: ‘strncasecmp’ was not declared in this scope
   if ( strncasecmp( name, "soma", 4 ) == 0 ) {
```

Another problem is gettimeofday in random number generator. There may be other similar cases of non-standard functions that hurt portability.

**Comment by dilawar** [comment]
This script tests the implementation http://coliru.stacked-crooked.com/a/7e040486237dd6fc
