### ISSUE TITLE
Gsolve gives a segfault with multithreaded branch 

### ISSUE THREAD

**Issue by rahulgayatri23** [BhallaLab/moose-core#116]
[onoff42.zip](https://github.com/BhallaLab/moose-core/files/272412/onoff42.zip)

This is the script that gives segfault when useGssa = True.

**Comment by dilawar** [comment]
Missing model files in zip folder.

**Comment by rahulgayatri23** [comment]
OH yeah sorry.
Here they are 
[Models.zip.zip](https://github.com/BhallaLab/moose-core/files/272550/Models.zip.zip)

**Comment by dilawar** [comment]
Confirmed. Segfault with BOOST solvers. Works well with GSL solver. Attaching compete model with correct paths. 

[onoff_model_issue116.zip](https://github.com/BhallaLab/moose-core/files/275771/onoff_model_issue116.zip)

**Comment by dilawar** [comment]
Integrated into `master` branch. Merged `master` into `multithreaded` branch. Reopen it if issue is not resolved.
