### ISSUE TITLE
Fix cmake for cygwin build

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose-core#117]
The cmake build finished with `make install` currently builds pymoose, but on cygwin the file _moose.so should be named _moose.dll and have 'x' permission turned on. Manually doing these changes works, but it will be desirable for the install script to do this automatically.

**Comment by championswimmer** [comment]
@subhacom  
Cmake version > 2.8.6 makes .dll automatically on calling the add_library() function. Have you built with Cmake > 2.8.6 ?

**Comment by subhacom** [comment]
I am using cmake version 3.3.2.

**Comment by dilawar** [comment]
There is no plan to support cygwin anymore. On windows 10, MOOSE can be installed using `bash/ubuntu`
