### ISSUE TITLE
Better mechanism for handling VERSION 

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#12]
Currently there are two place where moose version is hard-coded: cmake file, and python setup.py file. This may cause some error some day. Move the version information to one place.

**Comment by pgleeson** [comment]
+1, and ideally make the current version accessible with:

    import moose
    print moose.__version__

**Comment by dilawar** [comment]
Version is generated using `git tag`, e.g. today's version at this commit is:  ghevar_3.0.2-beta.2-233-g7112112
