### ISSUE TITLE
Problem in xml files of channel kinetics

### ISSUE THREAD

**Issue by Aindrila100** [BhallaLab/moose-core#127]
[kad.xml.txt](https://github.com/BhallaLab/moose-core/files/319772/kad.xml.txt)

When I use these channel kinetics instead of the original ones, I am getting an error as "Overflow error:Math range error" .

If I change the value of v to such that the exp term is close to exp(2/3), then my laptop is hanging while trying to run the narayanan model.

File is attached as txt file.

**Comment by dilawar** [comment]
Overflow usually happens when divide by very small number of raised to a unusually large power. Check if any of the expression in your XML files tends to blows up towards infinity.

**Comment by subhacom** [comment]
If you have not figured this out yet, the n gate in your channel model has both alpha/beta and tau/inf, and if I understand correctly, there should be only one pair. Moreover they are inconsistent (tau = 1/(alpha+beta) and inf=alpha/(alpha+beta)) and if I use your formulae, the results are completely different.

**Comment by dilawar** [comment]
Reopen it if the issue is still valid.
