### ISSUE TITLE
Changed moose.SBML API

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#156]
Previously `moose.readSBML` and `moose.writeSBML` functions were related to SBML loading and writing models.

Currently these has been changed to `moose.SBML.mooseReadSBML` and `mooseSBML.mooseWriteSBML` . Should they be mapped to `moose.readSBML` and `moose.writeSBML`?

Ideally they should be. I am not sure how they are used in moose-gui. If I change them in moose-core, it might break the moose-gui code. @hrani  comment?

**Comment by hrani** [comment]
What do you mean by mapped to moose.readSBML moose.writeSBML?

currently moose.readSBML or moose.writeSBML doesn't exist to map!

Earlier it had C++ class and wrapper, but now none.
one needs run

import moose.SBML
moose.SBML.mooseReadSBML()
moose.SBML.mooseWriteSBML()

or
from moose.SBML import *

mooseReadSBML()
mooseWriteSBML()

**Comment by dilawar** [comment]
That will break some examples , and snippets. See if documentation has same
function mentioned.

By mapping i meant that these can be renamed to old names.

**Comment by hrani** [comment]
Which are example and snippets which is breaking bcos I had fixed it.

**Comment by dilawar** [comment]
Snippet has be fixed by this commit long time back.
https://github.com/BhallaLab/moose-examples/commit/37ad1004779ca2dda69750ae70bb98fb9c3fd867

Seems like only file has old api call was a test script. I'll change that now.

I still think that `moose.readSBML` is better than `moose.mooseReadSBML` function.

**Comment by dilawar** [comment]
Additionally couple of lines from documentation needs to be cleaned up 
 https://github.com/BhallaLab/moose/search?utf8=%E2%9C%93&q=readSbml

**Comment by hrani** [comment]
In most of the files anything related readSBML, writeSBML are commented.
docs folder is not update, b'cos builtins_classes folder doesn't exist.

**Comment by dilawar** [comment]
Here is the proposal.

I'll expose two functions `moose.readSbml` and `moose.writeSbml`. They  map
to  moose.SBML.mooseReadSBML etc.  These functions will be available by
default if libsbml is installed else calling them produce a warning
indicating that libsbml is not installed and instructions on how to install
this package.

New API will continue to work as usual.

**Comment by dilawar** [comment]
Added two function `readSBML` and `writeSBML` to moose.py file. 

Added docstring to both functions. They call appropriate functions from moose.SBML.readSBML.mooseReadSBML and moose.SBML.writeSBML.mooseWriteSBML functions.

Pull request #157  contains these changes along with minor changes in cmake files.

**Comment by dilawar** [comment]
The release candidate (branch chamcham) has the following API call

```
moose.mooseReadSBML
moose.mooseWriteSBML
moose.mooseKriteKkit
````
etc.

**Comment by hrani** [comment]
I am assuming it's mooseWriteKkit?

**Comment by dilawar** [comment]
Yes. Fixed. @hrani
