### ISSUE TITLE
Replace `pygraphviz_layout` by a custom solution for both python2 and python3 

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#158]
To avoid dependency on networkx (pygraphviz), the layout computation for SBML models should be done by a local engine with minimum dependencies. Additionally, it should also work with both python2 and python3. 

Writing a custom layout engine is probably too big a task.

One can use graphviz python module.  This can be done by using the python-gv module. Following snippets shows how to do it.

```
import gv

def pos_of_node( node ):
    return gv.getv( node, "pos" )

def layout( g ):
    gv.layout( g, 'neato' )
    gv.render( g )
    n1 = gv.firstnode( g )
    n2 = gv.nextnode( g, n1 )
    print [ pos_of_node( x ) for x in [ n1, n2 ] ]

def main( ):
    test( )

def test( ):
    text = '''digraph g {
        a -> b;
        b -> c;
    }'''
    g = gv.readstring( text )
    layout( g )


if __name__ == '__main__':
    main()
```

```
python script.py 
['-37.382,60.934', '6.6387,3.6105']
```

This does the job but unfortunately `gv` is not available for python3.  https://pypi.python.org/pypi/graphviz-python. Added a ticket  http://www.graphviz.org/mantisbt/view.php?id=2606 

Other alternative is https://pypi.python.org/pypi/graphviz  which is available for both python2 and python3. 

```
pip3 install graphviz --user
Collecting graphviz
  Downloading graphviz-0.5.2-py2.py3-none-any.whl
Installing collected packages: graphviz
Successfully installed graphviz-0.5.2
```
This installs just fine. Not sure if one can compute the layout using it https://github.com/xflr6/graphviz/issues/28

**Comment by souravsingh** [comment]
@dilawar I would like to provide some help in the issue.

**Comment by dilawar** [comment]
@souravsingh Thanks. We follow the fork/pull-request based flow. 

Ideally we would like to get the layout coordinates of all SBML elements. You can normalize them between (0,0) (lower left) to (1,1) (upper right).

Graphviz default `dot` usually does not do a good job in placing the nodes. `neato` layout engine is decent. But personally, I've always like force/spring based layout computations as done by http://www.tcs.uni-luebeck.de/downloads/mitarbeiter/tantau/2012-gd-presentation.pdf and https://bl.ocks.org/mbostock/4062045 

good luck.

**Comment by hrani** [comment]
@souravsingh <https://github.com/souravsingh>
I have already working on it, with networkx,  nx.graphviz_layout(G, prog =
'dot') had given me a good layout with decent node spacing for number of
models that I had tried. I had replace this for nx.spring_layout, since I
discovered higher version of networkx with pygraphviz has a bug.

Layout-ing is not specific to SBML element, I am trying to auto layout
chemical models is being modelled in moose or SBML models that is read,
which is used for displaying in GUI.
I am still exploring.

HarshaRani

**Comment by souravsingh** [comment]
Hmm, looks like no one from outside Bhalla Lab is allowed to contribute to the project. You can take the issue @hrani

**Comment by dilawar** [comment]
@sauravsingh . This is not entirely true. You are most welcome to send the
pull request any time. You can always drop an email to the developer in
case of the doubt. We had couple of contributions in the past. There is
always some a chance of communication gaps when communicating online.

If you prefer, you can contribute to other open issues or open issue which
you feel MOOSE is lacking.

best,
    Dilawar

**Comment by dilawar** [comment]
The library `networkx` is being used to compute the layout. It is now in pymoose dependencies. If import fails due to missing `pygraphviz` library, the related functions will with raise exception. 

it is up-to user to make sure that `networkx` plays nicely with `graphviz` via `pygraphviz`.
