### ISSUE TITLE
Missing module `numpydoc` when generating documentation

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#17]
The script `docgen` uses `doxygen` and `python-sphinx` to generate moose-document. Currently build fails with error that  `module numpydoc is not found`.

This module is not a not part of `python-sphinx` package on various (perhaps all) distribution. Also rpm packages are not available for this. This causes build failure of `moose-doc` package on many RPM based distributions; even on Ubuntu. 

Currently moose-doc is an empty package till a easier solution to build doc is found. 

- Configure doc build in a way that it does not uses `numpydoc` (and any module which is hard to find as a package on all Linux distros).
- Build doc offline (on development machine) and distribute them along with source i.e. no need to build document when build packages. This will also reduce the dependency list on build time 

I prefer the first solution since `python-sphinx` is available in most of the Linux platform I am building for.

**Comment by dilawar** [comment]
Commenting out `numpydoc` extension inf user/py/conf.py file. This builds the doc.

**Comment by aviralg** [comment]
numpydoc is a pure python module. Assuming that the system lacks pip, we can just wget the following url - 
https://pypi.python.org/packages/source/n/numpydoc/numpydoc-0.5.tar.gz#md5=6feac1f625ad0df5a11c7b60f920ac1b
untar it, and run 
    python setup.py install. 

This will install numpydoc module.

I didn't set up the sphinx documentation system but I believe if numpydoc dependency helps build better documentation, we should use it. I have reassigned the issue to Subhasis, for his inputs. I can make the necessary changes based on his suggestion.

**Comment by dilawar** [comment]
During packaging, downloading of external source files are not allowed. For packaging purpose, the rule of thumb is, if a package could not be found in standard repositories then it has to be included in source tree.

Unless the dependency is essential, it should not be enabled else it would break the build for packaging.

I have disabled the `numpydoc` module for building packages. The build passing file and documents generated looks OK wihtout it. I think subha needs to say final word on it.

**Comment by aviralg** [comment]
I will grep over docs and see if any `numpydoc` extension is being used for documentation. He may have included it with the hope of using it in the future.

Do you always get `python-sphinx` and `doxygen` preinstalled on the systems you are building the documentation  package? How do you build in general if you require some library which is not present on the system which is building the package? Or is the restriction of not downloading packages more of a strongly recommended practice in the community for building doc packages?

**Comment by dilawar** [comment]
`python-sphinx` has huge dependency; it brings in latex and various other suits. On Ubuntu, OpenSuse, and Fedora; it is available but on some version of debian, centos, and rhel.

The best way out of it to generate the doc offline in html format and distribute it with the package. Currently only Launchpad (Ubuntu) and Debian are building doc. On others, moose-doc is empty package. 

if these packages are not provided by the standard distribution on Open Build Service, there is not way they can be installed during packaging. May be Fedora_People and SIG on CentOS might have more options during packaging but that I have not explored.

**Comment by subhacom** [comment]
numpydoc/napoleon enhance the formatting. You are welcome to comment it out for packaging, but the online version of the documentation should be built with numpydoc enabled. Also, readthedocs.org supports both numpydoc and napoleon if that is the way you are going with this.
