### ISSUE TITLE
which tool is handling the documentation through help(moose.x) and moose.doc(x)?

### ISSUE THREAD

**Issue by malav4994** [BhallaLab/moose-core#172]
@subhacom
When given the command "help(moose.vec)"
It not only produces the data put in comment in moose/pymoose/vec.cpp, but also some functions from the class, which moose.vec inherits.

For example,
 |  Methods defined here:
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x.x) 
 |  
 |  __delattr__(...)
 |      x.__delattr__('name') <==> del x.name

Can you please help finding out which tool is generating data through help(moose.vec) and also moose.doc(vec)? So that we can disable the functionality of generating data from parent classes.

Also to mention that help(moose.x) and moose.doc(x) generates different output. Why so?

**Comment by subhacom** [comment]
The relevant functions for `moose.doc()` are in `moose-core/python/moose/moose.py`. This function and its helpers are aware of moose documentation system and tries to collect the documentation strings from `Finfo` and `Cinfo` definitions.
`help()` however is a python builtin and uses `__doc__` attribute in a class as visible to Python. In the C interface these are defined as the field `tp_doc`. These docstrings are specified using `PyDoc_STRVAR` macro in the files in `moose-core/pymoose` directory.
The class specific documentations are populated in the `moose-core/pymoose/moosemodule.cpp::defineClass` function (`tp_doc` field). 
Check the sourcecode of [pydoc ](https://docs.python.org/2/library/pydoc.html)module to understand how the builtin `help` function works.
