### ISSUE TITLE
Make in debugging mode is giving errors

### ISSUE THREAD

**Issue by mickyaero** [BhallaLab/moose-core#174]
After executing "$ cmake -DDEBUG=ON .." the following libraries were not found
""""
-- Could NOT find Curses (missing:  CURSES_LIBRARY CURSES_INCLUDE_PATH) 
-- Could NOT find Readline (missing:  Readline_INCLUDE_DIR Readline_LIBRARY) 
""""
Then after executing "$ make"
""""
moose-core/synapse/testSynapse.cpp:158:6: error: ‘class SeqSynHandler’ has no member named ‘setResponseScale’
  ssh.setResponseScale( 1.0 );
      ^
""""

The complete gist can be found :- 
https://gist.github.com/mickyaero/7330e915a250a29e74d413d7db1588c7

**Comment by dilawar** [comment]
Check if the recent commits  fixes this issue.

**Comment by dilawar** [comment]
Closing this issue since there is no update.
Open it again if issue persists.
