### ISSUE TITLE
MOOGLI extension does not build with gcc-4.7.2 on Debian-7

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#18]
MOOGLI fails to build on `debian-7.0`. Compiler `gcc-4.7.2` emits an internal error. Most likely a gcc bug. Testing if this passes after some modification, else report bug on GCC.

~~~~~
from /home/dilawar/moose-full/moose-core/python/moogli/src/core/Compartment.cpp:1:
/usr/include/c++/4.7/bits/stl_pair.h: In instantiation of 'constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = osg::Vec3f&; _U2 = float&; <template-parameter-2-3> = void; _T1 = const osg::Vec3d&; _T2 = double]':
/home/dilawar/moose-full/moose-core/python/moogli/src/core/Compartment.cpp:24:62:   required from here
/usr/include/c++/4.7/bits/stl_pair.h:137:68: internal compiler error: in build_data_member_initialization, at cp/semantics.c:5790
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccMTv4K9.out file, please attach this to your bugreport.
~~~~~

**Comment by aviralg** [comment]
Debian 7.0 was released in the year 2013. GCC 4.7.2 was released in 2013. In fact GCC 4.7.x with x > 2 also exist. They must have fixed this bug. Try testing with GCC 4.7.4  before raising an issue with GCC. This seems like a basic bug which must have been discovered and corrected long time back. If vanilla Debian 7.0 comes with GCC 4.7.2 then try upgrading to ensure that GCC gets upgraded.
