### ISSUE TITLE
python-2.6 support?

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#182]
Currently `import moose` fails on CentOS-6. MOOSE builds fine with python-2.6 but the package is broken. Due to missing `Counter` in `collections` in default python installation on CentOS-6 i.e. python-2.6. `Counter` has been used in multiple places in moose-python.

Is there a plan to support python-2.6 or the one needs python-2.7 to be able to `import moose`?

**Comment by hrani** [comment]
fixed
https://github.com/BhallaLab/moose-core/commit/9373d1bc16fbac0992d8d15991df4d0bb677ec02
