### ISSUE TITLE
Huge runtime for external calcium test in hsolve.

### ISSUE THREAD

**Issue by dharmasam9** [BhallaLab/moose-core#192]
Test case https://github.com/dharmasam9/moose-core/blame/master/tests/python/test_hsolve_externalCalcium.py is taking almost 2 minutes to run. This is making it hard to fix issue  https://github.com/dharmasam9/moose-core/issues/33 .

**Comment by dilawar** [comment]
You can probably reduce run time by changing the value in `moose.start( )` . On our machine, this test takes couple of seconds to complete (without cuda).
