### ISSUE TITLE
moose compilation messages too far down in travis log

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose-core#26]
Online travis-ci log gets filled with the build/install messages for depedencies and it gives up displaying logs long before moose compilation starts. A way to redirect the non-moose build outputs and keep only the moose build output will be more useful.

**Comment by dilawar** [comment]
Redirecting the output log of build-dependencies to `/dev/null`. Only moose build log are dumped to `stdout`. This should reduce the size of build-log.
