### ISSUE TITLE
Need time variable `t` support in `moose.Function`

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#27]
Currently `x`, `y` and `c` are supported by `moose.Function`. It will be nice to have support for variable `t` e.g. function expression like `sin(t) + cos(t)` without the need to connect `t` with any `moose.Clock`.

**Comment by subhacom** [comment]
Fixed in Issue27 branch.

**Comment by dilawar** [comment]
Does it working with Gsolve ? I have an example where expression with 't' in it does not seem to work, there is no error or warning either.
