### ISSUE TITLE
Problem finding compartments in SbmlReader.cpp

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#29]
Following lines in sbml/SbmlReader.cpp return EMPTY vector of ChemCompts since base_.path() is already a compartment and ChemCompts MAY NOT exist as its children.

~~~
+            string simpath = base_.path() + "/"+comptName+"/##[]";
+            wildcardFind( comptpath, compts );
~~~

Currently I am working without prefixing base_.path() to wildcard expression. One can also pop the very last expression from base_.path() before prefixing. 

- Migrated from sourceforge.

**Comment by hrani** [comment]
Can you tell me where did you find this bit of code.
And if wildcardFind doesn't find compartment if you path is /modelname/compartment then its wildcardFind problem rather than SbmlReader.cpp. I can just providing the path to wildcardFind and get return value

**Comment by dilawar** [comment]
I can't recall it now. It's been so long since I reported this bug. If you can't
find any evidence, close it.

best,
     Dilawar

**Comment by hrani** [comment]
In-case if you find it out again this will be wildcardFind feature problem rather than "sbmlreader" file.
