### ISSUE TITLE
seg fault while showfield(EndoMesh)

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-core#326]
1.EndoMesh's numDimensions is 1, it should be 3

2.Getting seg fault vGetVoxelVolume() while query showfield on EndoMesh

import moose
moose.Neutral('/n')
EndoM = moose.EndoMesh('/n/EN')
moose.showfield(EndoM)

 SIGSEGV, Segmentation fault.
0x00007fffe1a76909 in EndoMesh::vGetVoxelVolume() const

**Comment by upibhalla** [comment]
Fixed both in latest commit.
