### ISSUE TITLE
moose.connect on `y0`, `y1`, etc. is ordered dependant

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#33]
Currently, if `y1` field is connected before `y0` field of a `moose.Function`, the output of function is not correct. To get  the correct output, one has to make sure that all `ys` are connected in increasing order. 

Let me know if a MWE is needed. Probably related to https://github.com/BhallaLab/moose/issues/163

**Comment by subhacom** [comment]
This is documented behaviour:
http://moose.ncbs.res.in/pymoose/moose_cookbook.html#computing-arbitrary-functions-on-the-fly
and unrelated to the bug referred to.
On Oct 1, 2015 2:49 AM, "Dilawar Singh" <notifications@github.com> wrote:

Assigned #33 <https://github.com/BhallaLab/moose-core/issues/33> to
@subhacom <https://github.com/subhacom>.

—
Reply to this email directly or view it on GitHub
<https://github.com/BhallaLab/moose-core/issues/33#event-423902818>.
