### ISSUE TITLE
 latest moose-core (commit number 0e85a5) compiled with python2.7 with gcc 4.9.2?

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-core#398]
export GSL_ROOT_DIR=/softwares/gsl-2.1/
>moose-core/_build
/softwares/cmake3.17/bin/cmake ..
-DPYTHON_INCLUDE_DIR="/usr/include/python2.7/"
-DPYTHON_LIBRARY="/usr/lib64/" -DPYTHON_EXECUTABLE="/usr/bin/python"

[cMakereport.txt](https://github.com/BhallaLab/moose-core/files/4342653/cMakereport.txt)

[CMakeCache.txt](https://github.com/BhallaLab/moose-core/files/4342649/CMakeCache.txt)

I think it compiles with out any error, pythonpath is set

 `import moose`
[INFO] Plot utilities are not loaded due to 'Matplotlib requires pyparsing>=2.0.1; you have 1.5.6' 
`moose.__path__`
['~/moose-core2/python/moose']
`moose.loadModel('Anno_acc12.g','/test12','ee')`
<moose.vec: class=Neutral, id=448, path=/test12>
`moose.reinit()`
`moose.start(10)`
with 'ee' as solver its fine reinit works and runs

 **moose.mooseAddChemSolver("/test12","gsl")**
  File "~/moose-core2/python/moose/moose.py", line 264, in mooseAddChemSolver
    print( chemError_ )
UnboundLocalError: local variable 'chemError_' referenced before assignment 

**moose.loadModel('Anno_acc12.g','/acc12','gsl')**
  File "~/moose-core2/python/moose/moose.py", line 112, in loadModel
    chemError = _chemUtil.add_Delete_ChemicalSolver.mooseAddChemSolver(modelpath, method)
NameError: global name '_chemUtil' is not defined

`moose.le('/test12')`
segfault

**Comment by dilawar** [comment]
This is related to  #397 and caused by the import failure of matplotlib.

**Comment by dilawar** [comment]
There should be helpful message when import failed in such cases.

**Comment by dilawar** [comment]
Segfault even with 8d68b6d . Doen't matter which commit I use, I get seg-fault with default python2/3 compiled with gcc.4.8.5 .
