### ISSUE TITLE
Error parsing equations

### ISSUE THREAD

**Issue by bhanu151** [BhallaLab/moose-core#414]
Fig6_generate_data.py threw a seg fault when compiling an equation. The code was run using Pymoose Version 3.2.1.dev20200519. Previous versions 3.2.1.dev20200428 and 3.2.0.dev20200107 also threw the same error. 

However the code did not throw any errors when tested with moose-core commit 1b38d64f451a6b5b0d6caf610376d6ba3ba93cb6 using Python2, that was compiled and built on the system.
 
Command to run - python3 Fig6_generate_data.py --fnumber 0 --sequence 1234

Check output.txt for the specific error.

[output.txt](https://github.com/BhallaLab/moose-core/files/4741662/output.txt)

[Supplementary.tar.gz](https://github.com/BhallaLab/moose-core/files/4741655/Supplementary.tar.gz)

**Comment by dilawar** [comment]
The PR #415 is still pending review and merge. May be you can remind the maintainers and lead developers.

**Comment by dilawar** [comment]
This can be closed now. #415 is merged.

**Comment by hrani** [comment]
Fixed in #415
