### ISSUE TITLE
Python 3.9: test_pyrun segfaults

### ISSUE THREAD

**Issue by sanjayankur31** [BhallaLab/moose-core#419]
Hello,

While building moose for Fedora 33+, `test_pyrun` segfaults with python 3.9. 

```
8: Test command: /usr/bin/python3 "/builddir/build/BUILD/moose-core-3.1.5/tests/python/test_pyrun.py"
8: Environment variables:
8:  PYTHONPATH=/builddir/build/BUILD/moose-core-3.1.5/build/python
8: Test timeout computed to be: 1500
 8/13 Test  #8: test_pyrun .......................***Exception: SegFault  0.32 sec

```

I'm not currently sure of what's causing this. Would you have any ideas? We'll be happy to provide more information if you can tell us what's needed.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1808668

Moose versions this is applicable to: 3.1.4 and 3.1.5.

**Comment by dilawar** [comment]
@sanjayankur31 #420 has the fix for this. The branch `chamcham` is for `3.1.x` release. 

@upibhalla @hrani  If you plan to merge #420, you may have to bump the version to `3.1.6` and create a tag.

**Comment by sanjayankur31** [comment]
Thanks, I can confirm that #420 fixes the segfault. I've updated moose in NeuroFedora to 3.1.5 now and included this patch there also.

**Comment by dilawar** [comment]
https://github.com/BhallaLab/moose-core/pull/420/commits/665c532745987fb1c7a8fc2a9a57bffa330480b4 has a better fix for this. My previous fix causes a memory leak.
