### ISSUE TITLE
issues with "New python bindings using pybind11"

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-core#423]
moose.le('/') works but
1. moose.le('/r') which is not defined or created it gives 
**moose.element: /r does not exist!
Segmentation fault (core dumped)**

2. isinstance of super class gives False
n = moose.Neutral('/n')
c = moose.CubeMesh('/n/cube')
isinstance(c,moose.ChemCompt)
returns False should be  True as CubeMesh is inherited from ChemCompt which was the True before new python bindings

**Comment by dilawar** [comment]
The PR #424 fixes the seg-fault issue with `moose.le`.

`isinstance` does not work as before in new binding. See https://github.com/BhallaLab/moose-core/pull/404#issuecomment-609676670 and https://labnotes.ncbs.res.in/bhalla/new-python-bindings-are-alpha-now and following discussion on issue #404. 

The current recommendation is to use `isA` as you have also mentioned in https://github.com/BhallaLab/moose-core/pull/404#issuecomment-609797678 (not sure though what you meant here). Nonetheless, following is the behavious of new bindings:

```python
n = moose.Neutral('/n')
c = moose.CubeMesh('/n/cube')
print(isinstance(c, moose.CubeMesh))      # True
print(isinstance(c, moose.ChemCompt))     # False 
print(c.isA['ChemCompt'])                 # True
```

The line `isinstance(c, moose.ChemCompt)` is no longer `True` in new bindings. You **must** use `c.isA['ChemCompt']` (notice the square bracket, though `()` also works).

**Comment by hrani** [comment]
Yes my mistake, I had changed this in the moose-gui, will do for SBML reader and writer also.
