### ISSUE TITLE
seg fault moose.delete('/test') for non exist object

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-core#429]
when object which doesn't exist if ask to delete we get Seg fault
import moose
moose.delete('/test')  #where '/test' is neither created nor exist then we get seg fault 

Works: 
import moose
moose.Neutral('/test')
moose.delete('/test')    #works

**Comment by dilawar** [comment]
#430 fixes it. Also somewhat related to #424

**Comment by hrani** [comment]
Build failing for OSX, lot of warning messages

**Comment by dilawar** [comment]
Both build are passing https://travis-ci.org/github/BhallaLab/moose-core/pull_requests. Linker warnings generated by clang https://travis-ci.org/github/BhallaLab/moose-core/jobs/730360830 are not critical.
