### ISSUE TITLE
type_traverse error on python2.6/CentOS-6

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#46]
~~~~~
dilawar@nargis ~ $
python2.6
Python 2.6.6 (r266:84292, Sep 11 2012, 08:34:23) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import moose
python2.6: Objects/typeobject.c:2673: type_traverse: Assertion `type->tp_flags & (1L<<9)' failed.
Aborted
~~~~~

However, with python2.7, its working fine. `export PYTHONPATH=/usr/lib/python2.6/site-packages`

**Comment by upibhalla** [comment]
Dear Dilawar,
     But Ghevar has Python 2.7
Best,
     Upi

**Comment by dilawar** [comment]
Dear Upi,

Its on nargis cluster. CentOS official python is 2.6. MOOSE package is compiled
with this python. However, tt does not work with python2.6 but works with 2.7!


best,
    Dilawar

**Comment by dilawar** [comment]
No such issue Virtualbox with centos-6.7. Probably some issue on Nargis.

**Comment by subhacom** [comment]
Dear Dilawar,
  I remember Chakrapani and colleagues had installed python2.7 on nargis
and both I and Sahil compiled and ran moose on it.
  I would not worry about python2.6 and older versions in any case.
Best,
   Subha

**Comment by dilawar** [comment]
Local compilation is fine on nargis. Issue is with installation of upstream built moose package which is giving this issue. Not a serious one since it is working with python2.7 after linking `/usr/lib/python2.6/site-packages/moose` to `/usr/lib/python2.7/site-packages/moose`.  Leaving it open in case someone faces this issue with their installation.

**Comment by subhacom** [comment]
I see. I would suggest that you leave it as source package and put
instructions for centos 6 or keep the installation target python2.7. Centos
is anyways years behind regular redhat distros and now the 7 is out it
seems.
So better to see if 7 has python2.7 and package for that.

**Comment by dilawar** [comment]
Probably an issue with Python release on CentOS-6. Works fine after `yum update` on CentOS-6.
