### ISSUE TITLE
Fatal Linker Error (LNK1107) While Building _moose.cp311-win_amd64.pyd

### ISSUE THREAD

**Issue by ashxhuman** [BhallaLab/moose-core#495]
I encountered a linker error (LNK1107) while building `_moose.cp311-win_amd64.pyd` on Windows using clang++, following the instructions in [WindowsBuild.md](https://github.com/bhallalab/moose-core/blob/master/WindowsBuild.md). The error indicates that the file `external\libsoda\libsoda.a` is invalid or corrupt. The detailed error message is as follows:
```
external\libsoda\libsoda.a : fatal error LNK1107: invalid or corrupt file: cannot read at 0xC9E4
clang++: error: linker command failed with exit code 1107 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
### Steps to Reproduce
```
micromamba create -n moose meson ninja meson-python gsl hdf5 numpy matplotlib pkg-config pybind11[global] clang -c conda-forge
micromamba activate moose
git clone https://github.com/BhallaLab/moose-core --depth 50 
pip install .
cd moose-core
meson setup --wipe _build -Duse_mpi=false --buildtype=release
ninja -v -C _build 
```

<details>
<summary>Here is the full error </summary>

<img width="944" alt="Screenshot 2024-11-28 121253" src="https://github.com/user-attachments/assets/d0cf5e37-6fb6-407e-8d61-c7bb466c79ed">
</details>

**Comment by subhacom** [comment]
Adding `--vsenv` to the meson setup command, and then using `meson compile` instead of `ninja` fixes this. Updated in commit https://github.com/subhacom/moose-core/commit/0c8a6da5c662db8bdaea43d001e40cd1d423dad9
