### ISSUE TITLE
Cleaning up `python/moose` directory

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#75]
There are few modules/files scatters in `python/moose` which needs to be cleaned-up. Few of them I added long time back. I am removing them from this repository.  May be they can be put back in `contrib` folder or something similar. Right now the focus is to cleanup the tree.
- [x] backend; builds a graph from moose-internal messages. Dilawar, ~~Planned to be deleted~~. Removed.
- [x] topology; process the graph generated by `backend`. Dilawar. ~~Planned to be deleted~~ Removed.
- [x] kkit . ~~@subhacom~~ @hrani  
- [x] neuroml, In working condition. Often used. May be some documentation is needed.
- [x] `print_utils.py`, `verification_utils.py`, and `sim_utils.py`. Dilawar. I need to document them. They have some useful functions which I often use: e.g. for saving `moose.Tables` to csv file and plotting them. Need better documentation. 
- [x] neuroml2. @subhacom It can still read morphology-only files. Ion channel and concentration needs updating. Waiting for upstream neuroml2 schema to stabilize.
- [x]  genesis. @hrani .  

In addition to these, in `python` directory, I worked on `libmumbl`. Disable its packaging till its ready. Retain it for development.

**Comment by dilawar** [comment]
Adding concerned developers: @hrani , @subhacom

**Comment by subhacom** [comment]
kkit directory contents seems to be @dilawar 's work. Please check if it is still needed. Remove otherwise.

**Comment by hrani** [comment]
Kkit directory in moose-core/python directory is mine I am using python
version for writing to genesis file format. Slowly I will remove
kinetics/writeKkit.cpp file later, once I am full confidence of removing.
