### ISSUE TITLE
readSBML core dumped

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-core#85]
Orginally created by <a href=https://github.com/MelanieIStefan>MelanieI Stefan</a>  under moose moved to moose-core

I have used moose.readSBML successfully in the past, but now I get the following error message:

**\* Error in `python': free(): invalid pointer: 0x00007ffff3b8d9e8 ***
Aborted (core dumped)

Running the latest version of moose and Python 2.7.10 on Ubuntu 15.10

Also I realise that the loadSbml.py snippet has gone from the snippets folder, so maybe this means you are working on this already.

**Comment by hrani** [comment]
Dear Melaniel, 
"loadSbml.py " file exist in moose-example/snippets
https://github.com/BhallaLab/moose-examples/blob/master/snippets/loadSbmlmodel.py

And regarding core dump I will check, until Ubuntu 14.04 and python 2.7.6 it seems to be fine. Let me grab a system check and let you know

**Comment by dilawar** [comment]
@MelanieIStefan The SBML support will be at python level. The C++ interface is being phased out. Most likely, the API call will not change.

**Comment by dilawar** [comment]
Closed. Invalid since libsbml support is now at python level.
